### ISSUE TITLE
See if the SCL versions can be made into a template

### ISSUE THREAD

**Issue by xksteven** [centerforaisafety/cerberus-cluster#1]
In this directory: https://github.com/centerforaisafety/cerberus-cluster/tree/master/playbooks/roles/packages/tasks

**Comment by andriy-safe-ai** [comment]
Do we still want to keep this issue open?

**Comment by andriy-safe-ai** [comment]
@steven-basart 

I don't think this would make the code cleaner. There are only a few SCL versions and adding more abstraction wouldn't simplify the code. Just my two cents.

**Comment by steven-basart** [comment]
Happy to close it. It's really low priority anyways.
