### ISSUE TITLE
Manually add mount targets

### ISSUE THREAD

**Issue by steven-basart** [centerforaisafety/cerberus-cluster#101]
compute-permanent-node-
35,
48,
76,
84,
111,
128,
136,
153,
166,
171,
269,
323,
363,
365,
408,
485,
537,
587,
605,
608,
618,
719,
733,
746,
800,
863,
870,
871,
907,
912,
918,
990

**Comment by steven-basart** [comment]
Will update the above post when we add a mount target to said node.

**Comment by steven-basart** [comment]
Mount target IPs =
Login = 172.16.7.24
Bastion, backup = 172.16.0.71
172.16.4.99
172.16.7.110
172.16.6.39
172.16.6.21
172.16.4.10
172.16.5.161
172.16.7.78
172.16.7.208
172.16.6.93
172.16.4.247
172.16.7.203
172.16.4.111
172.16.5.48
172.16.6.91
172.16.6.62
172.16.4.92
172.16.5.35
172.16.6.58
172.16.6.144
172.16.6.147
172.16.4.24
172.16.5.18
172.16.4.51
172.16.5.233
172.16.4.158
172.16.4.84
172.16.5.149
172.16.7.249
172.16.6.30

**Comment by steven-basart** [comment]
```
sudo vim /etc/fstab
# update /data to IP
sudo umount /data
sudo mount /data
```

35 = 172.16.4.99

**Comment by andriy-safe-ai** [comment]
990 = 172.16.6.30

**Comment by andriy-safe-ai** [comment]
@steven-basart 
Is there anything left to do for this issue?

**Comment by steven-basart** [comment]
Nope but we do need a new issue to reassign mount targets when a node comes up.

**Comment by andriy-safe-ai** [comment]
The FSS has been deprecated. The mount targets are no longer needed and will be removed in #232. Closing.
