### ISSUE TITLE
Look into setting up a notification program for cluster status (drain etc)

### ISSUE THREAD

**Issue by rumiahkessel** [centerforaisafety/cerberus-cluster#118]

**Comment by rumiahkessel** [comment]
Can also be setup with [https://slurm.schedmd.com/strigger.html](https://slurm.schedmd.com/strigger.html) to use the mail program we currently use and send slack notifications as well. Alternatively can have it send to a channel in slack that all admins are in for publicity

**Comment by steven-basart** [comment]
I do too. Question is how long would it take to set up?
