### ISSUE TITLE
Review OCI Storage Prices

### ISSUE THREAD

**Issue by andriy-safe-ai** [centerforaisafety/cerberus-cluster#123]
We found pricing documentation that suggests significant prices increases for storage at OCI. 

Here is the link: https://www.oracle.com/cloud/price-list/#compute-image-artifact

Review what we are getting charged for Block Volumes, Object Storage, and File Storage per gigabyte per month.

**Comment by steven-basart** [comment]
![Screenshot 2023-06-21 at 1 39 51 PM](https://github.com/centerforaisafety/cerberus-cluster/assets/130421631/c3704750-7db0-45fb-b2d1-2e7e08dabb7b)

**Comment by andriy-safe-ai** [comment]
The link above no longer shows $0.45 FSS pricing. It doesn't look like prices will be increasing. It also won't matter due to our filesystem migration.
