### ISSUE TITLE
Add FSS snapshots

### ISSUE THREAD

**Issue by andriy-safe-ai** [centerforaisafety/cerberus-cluster#126]
Add snapshot policy. 

Schedule: Daily snapshots with 7 day retention.

**Comment by andriy-safe-ai** [comment]
Created Snapshot Policy with that creates daily snapshots that are retained for seven days. Attached the policy to our both our `/data` and `/home` FSS filesystems.

**Comment by andriy-safe-ai** [comment]
@steven-basart

**Comment by steven-basart** [comment]
This makes a snapshot of the whole FSS from data. It's there a way to have more done grained snapshots like of every directory in /data instead of all of /data

@andriy-safe-ai

**Comment by andriy-safe-ai** [comment]
@steven-basart I'm not sure what you mean by more fine grained. The snapshots have a file/directory hierarchy. You can view them in the .snapshots directory. You can access individual dirs and files. Is that what you mean?

If you want snapshots of only specific sub-dirs we'll need a different t solution or mount a separate fss for each user.
