### ISSUE TITLE
Switch from du to duc

### ISSUE THREAD

**Issue by xksteven** [centerforaisafety/cerberus-cluster#13]
for fss_usage.sh file

**Comment by steven-basart** [comment]
Steps to install:

```
# install required packages
sudo yum install tokyocabinet-devel cairo-devel pango-devel

wget https://github.com/zevv/duc/releases/download/1.4.5/duc-1.4.5.tar.gz
tar xvzf duc-1.4.5.tar.gz
cd duc-1.4.5/
./configure
make
make install
sudo make install
```

To run

```
sudo /usr/local/bin/duc index /data
# It saves it in a weird location so copy it over
sudo cp /root/.cache/duc/duc.db ~/.duc.db
```

View the data

```
duc info

duc ls -Fg /data
```

**Comment by steven-basart** [comment]
### Install dust

```
cd scripts
mkdir dust
cd dust
```

#### Install dependencies 

#### Install musl

```
wget https://www.musl-libc.org/releases/musl-1.2.2.tar.gz
tar -xvf musl-1.2.4.tar.gz
cd musl-1.2.4
./configure
make
sudo make install
cd ..
```

#### Install dust

```
wget https://github.com/bootandy/dust/releases/download/v0.8.6/dust-v0.8.6-x86_64-unknown-linux-musl.tar.gz
tar -xvf dust-v0.8.6-x86_64-unknown-linux-musl.tar.gz
cd dust-v0.8.6-x86_64-unknown-linux-musl/
sudo mv dust /usr/local/bin/ 
```

#### Run it

```
sudo /usr/local/dust /data
```

**Comment by andriy-safe-ai** [comment]
@steven-basart I think this is the best tool so far. Do you have any other tools you want to try next?

**Comment by steven-basart** [comment]
Dunno. There might be one or something we do to keep track of user storage history. 

Not as big of an issue right now but it was an issue before. 

We will need it again soon.

**Comment by andriy-safe-ai** [comment]
@steven-basart 

Are we still using the `fss_usage.sh` script to keep track of storage usage? I doesn't look like the `fss_du.log` file has been updated since June? 

1. Should we update the script to use `dust` instead of `du` or `duc`?
2. Should we setup a cron job to automatically run the script?
3. Should we setup an email notification that sends a copy of the log file?
4. Can we close this issue?

**Comment by steven-basart** [comment]
No we need to set something up where we can both measure the storage and keep track of it over time.

**Comment by trent-safe-ai** [comment]
@steven-basart is this closed?

**Comment by steven-basart** [comment]
Feel free to rename the issue or make a new one. @trent-safe-ai 

We need to set something up where we can both measure the storage and keep track of it over time. Haven't found a solution that does both or haven't implemented one yet.

**Comment by andriy-safe-ai** [comment]
Closing issue as we now have Weka Grafana for tracking overall filesystem usage and we can view per user usage through `weka fs quota list --all`.
