### ISSUE TITLE
[Epic] cluster portability 

### ISSUE THREAD

**Issue by steven-basart** [centerforaisafety/cerberus-cluster#137]
Issues (to be possibly created)

- code needs to be able to be deployed to more than 1 cluster
- need mechanisms to keep clusters in sync (GitHub actions to multiple locations)
- we need to find a good dev cluster that can mimic prod
    - determine if we have availability to spin up and down dev clusters
    - ideally would want to do this in CPU environment
- determine what services we provide

**Comment by andriy-safe-ai** [comment]
Closing this issue. I created two epics in ZenHub "Cluster Portability Epic" and "Development Environment Epic".
