### ISSUE TITLE
Didn't receive a slack status notification when 2 of the nodes went into drain on 7/10 (587, 618)

### ISSUE THREAD

**Issue by rumiahkessel** [centerforaisafety/cerberus-cluster#141]
For some reason did not receive a notification for two of the nodes in drain. Need to investigate.

**Comment by rumiahkessel** [comment]
Also seems that during the last few episodes of nodes going down it only sent notifications for one of the nodes. Is already setup to send all nodes and did so during the maintenance window. Continue monitoring and try to see why

**Comment by rumiahkessel** [comment]
The problem is because strigger only triggers on a drain state not on draining. So if a node gets stuck while draining we are never notified. No functionality for this is provided with strigger, so can only achieve it with cron.

**Comment by andriy-safe-ai** [comment]
@rumiahkessel 

I think we can close this issue. We get notified when a node has drained. We don't need to worry about a node draining as we shouldn't do anything to it until it has fully drained.
