### ISSUE TITLE
Add documentation for how to investigate compute nodes going down

### ISSUE THREAD

**Issue by andriy-safe-ai** [centerforaisafety/cerberus-cluster#143]
We have documentation for what to do if we have a compute node that goes down but we don't have a procedure for how to determine what the root cause of the issue was. 

The goal of this issue would be to create a systematic approach for how to determine the root cause of a node going down. 

A node going 'down' can take multiple forms. We are referring to situations when the node is draining, drained, down, stuck in draining, stuck in completing, etc.

**Comment by steven-basart** [comment]
We do have this section already:
https://docs.cais.tools/cais/cerberus/admin-docs/#investigation

However there is essentially "infinite" ways for something to go wrong so we don't need to make it extensive.  Expanding it a bit would be fine though.
