### ISSUE TITLE
Added a temp_qos QOS remove it by August 25

### ISSUE THREAD

**Issue by steven-basart** [centerforaisafety/cerberus-cluster#169]
Remove temp_qos by August 25th

**Comment by andriy-safe-ai** [comment]
@steven-basart 

Reminder set.

**Comment by steven-basart** [comment]
Thank you. 
Only other thing to check for is the "cluster" partition having a QOS. A QOS needs to be added to the partition for it to be valid and used.

**Comment by steven-basart** [comment]
"# Make sure the top level is aware of and has both qos"
 https://docs.cais.tools/cais/cerberus/admin-docs/#:~:text=%23%20Make%20sure%20the%20top%20level%20is%20aware%20of%20and%20has%20both%20qos

Not sure if the link works? It's part of the admin docs for setting it up

**Comment by andriy-safe-ai** [comment]
@steven-basart 

Yes, the `temp_qos` has been removed from the cluster partition.

```
sudo sacctmgr show cluster format=qos%100
                                                                                                 QOS 
---------------------------------------------------------------------------------------------------- 
                                                                          default_qos,restricted_qos 
```

**Comment by steven-basart** [comment]
Good to close
