### ISSUE TITLE
Integrate weka-mon with our grafana

### ISSUE THREAD

**Issue by steven-basart** [centerforaisafety/cerberus-cluster#179]

**Comment by trent-safe-ai** [comment]
Working through this on the headnode on our prometheus stack to test-
got to this part today will finish in the morning:
[opc@prometheus-headnode export]$ /usr/local/bin/weka-mon/export/export -v -c /usr/local/bin/weka-mon/export.yml
INFO:Timeout set to 10.0 secs
INFO:looking for token file auth-token.json
INFO:Checking for /usr/local/bin/weka-mon/export/auth-token.json
INFO:Using authfile /usr/local/bin/weka-mon/export/auth-token.json
ERROR:Weka API error caught: Login attempt failed
ERROR:Weka API error caught: Login attempt failed
ERROR:Weka API error caught: Login attempt failed
^CCRITICAL:SIGINT received, exiting
[opc@prometheus-headnode export]$

**Comment by trent-safe-ai** [comment]
Done PR for docs just added.
