### ISSUE TITLE
Grafana is still pulling from OCI instead of our own datastore

### ISSUE THREAD

**Issue by steven-basart** [centerforaisafety/cerberus-cluster#181]

**Comment by trent-safe-ai** [comment]
@steven-basart what do you mean 'pulling from OCI'? which dashboard?

**Comment by steven-basart** [comment]
This dashboard: 
https://graphs.cais.tools/d/oFYARa0Gk/oci-file-system-service-dashboard?orgId=1

**Comment by trent-safe-ai** [comment]
Note to self -  can implement k8s service now- influx db is robust enough- https://github.com/centerforaisafety/openmetrics/blob/main/oci_exports/oci_metrics_service.py

**Comment by andriy-safe-ai** [comment]
Our deployment of Grafana has changed. We are no longer using Prometheus nor OCI as the datastore. I verified this by looking at the active datastore Grafana and only Victoria Metrics is configured.
