### ISSUE TITLE
Mount Weka

### ISSUE THREAD

**Issue by andriy-safe-ai** [centerforaisafety/cerberus-cluster#183]
Update `/etc/fstab/` on all nodes to swap fss with weka. 

```
sudo vim /etc/fstab
# update 
172.16.6.58:/data /data nfs defaults 0 0
# to 
172.16.6.58:/data /mnt/fss/data nfs defaults 0 0

# then unmount /data
sudo umount /data

# mount /mnt/fss/data
sudo mount /mnt/fss/data

# create the directory tree if it doesn't exist
sudo mkdir /mnt/fss
sudo mkdir /mnt/fss/data

# check if fss was mounted correctly
cd /mnt/fss/data 
ls -l
```

login - done
bastion - done
backup - done
35 - swapped 
48 - swapped
76 - swapped 
84 - swapped
111 - swapped
153 - swapped
166 - swapped
171 - swapped
269 - swapped
323 - swapped
363 - swapped
365 - swapped
408 - swapped
485 - swapped
537 - swapped
587 - swapped
605 - swapped
608 - swapped
618 - swapped
719 - swapped
733 - swapped
746 - swapped
800 - swapped
863 - swapped
870 - swapped
871 - swapped
891 - swapped
907 - swapped
912 - swapped
918 - swapped
990 - swapped

**Comment by steven-basart** [comment]
Reboot all the nodes 1 by 1
run 
```
sudo mount -t wekafs default /data
```

**Comment by steven-basart** [comment]
We've mounted weka on all of the nodes.
