### ISSUE TITLE
Local storage getting eaten up on compute nodes

### ISSUE THREAD

**Issue by trent-safe-ai** [centerforaisafety/cerberus-cluster#186]

**Comment by trent-safe-ai** [comment]
Find out what is taking space on compute nodes get rid of it, remove it, etc.

**Comment by steven-basart** [comment]
Weka saves traces (i.e. logs of what happened or went wrong in /opt/weka/traces).  By default the storage takes up a lot of space and it is configured to leave only 3 GB free space.  

Went through and reconfigured the storage to only save 20 GB of data and allow for 10 GB of free space by default.

Command to be run on one of the compute nodes.
```
weka debug traces retention set --server-max 20GiB --client-max 20GiB --server-ensure-free 10GiB --client-ensure-free 10GiB
```
