### ISSUE TITLE
thanos timing receiver issue

### ISSUE THREAD

**Issue by ghost** [centerforaisafety/cerberus-cluster#199]
Thanos's eventually consistent write strategy is great and all but our instance is not getting all the data that the prometheus node pushing it's metrics to. 

We need to figure out why this is happening and fix the issue either within Thanos or with setting up Prometheus to have more than one main instance that is scraping metrics from instances and containers.

**Comment by trent-safe-ai** [comment]
It looks like thanos is starving for resources- will need to change it's requested to provide more when it bursts.
