### ISSUE TITLE
Need to update docs 

### ISSUE THREAD

**Issue by steven-basart** [centerforaisafety/cerberus-cluster#212]
`sudo mount -t wekafs default /mnt/weka` should become `sudo mount -t wekafs default /data`

Also need to create the local mounts folder on each new node.

**Comment by steven-basart** [comment]
This command will fail on the nodes where the 

folder /data/nodes_local/compute-permanent-node-### doesn't exist

```
sudo mount /mnt/localdisk
```

**Comment by andriy-safe-ai** [comment]
This is a doc issues. I created the following issue: https://github.com/centerforaisafety/eng-docs/issues/46

**Comment by andriy-safe-ai** [comment]
@steven-basart 

The localdisk folder for a compute node is created in the weka compatibility script.
