### ISSUE TITLE
Prepare for new Image OCI in Cerberus

### ISSUE THREAD

**Issue by ghost** [centerforaisafety/cerberus-cluster#242]

**Comment by trent-safe-ai** [comment]
When this is released:
* Deploy new dev cluster
* get a diff on rpm of prod and new dev env instances (bastion and compute, etc)
* prepare (with oracle) to spin up new HPC/BM nodes with updated images/code.

**Comment by andriy-safe-ai** [comment]
I created the new OCI images.
