### ISSUE TITLE
Build slurm resource/charge back model to be able to calculate per user cost.

### ISSUE THREAD

**Issue by ghost** [centerforaisafety/cerberus-cluster#249]
Create billing database based on billing factors of GPU, CPU and Memory and run a cron job every night that calculates resource consumption nightly and populates the billing database with that data.

Slurm Billing Process Flowchart

Start: Cron Job

Step 1: Collect Job Data

    Run sacct command with specific formatting options to collect job information including:
        JobID
        User
        Account
        Allocated resources (TRES, AllocCPUs, MaxRSS)
        State
        Elapsed time

Step 2: Process and Format Data

    Parse the sacct output and extract relevant data.
    Convert data into a format suitable for further processing.

Step 3: Calculate Resource Usage

    For each job:
        Calculate GPU hours based on allocated GPUs and elapsed time.
        Calculate CPU hours based on allocated CPUs and elapsed time.
        Calculate memory GB-hours based on MaxRSS and elapsed time.

Step 4: Calculate Cost

    For each resource type:
        Retrieve the corresponding billing factor from the resource billing factors table.
        Multiply resource usage by the billing factor to calculate the cost.
        Sum the cost of all resources to get the total cost for each job.

Step 5: Prepare Data for Insertion

    Organize the processed data into a format compatible with the database tables.
    Separate data for user and account tables for individual and group billing.

Step 6: Insert Data into User Table

    Insert user resource usage data (including jobID, user, date, GPU hours, CPU hours, memory GB-hours) into the user_resource_usage table.

Step 7: Insert Data into Account Table

    Insert account resource usage data (including jobID, account, date, GPU hours, CPU hours, memory GB-hours) into the account_resource_usage table.

Step 8: Commit Changes to Database

    Save the inserted data permanently in the database.

Step 9: Close Database Connection

    Disconnect from the database to avoid unnecessary resource consumption.

End

Subgraphs:

    Database:
        user_resource_usage: Stores individual user resource usage data.
        account_resource_usage: Stores account-level resource usage data.
    Resource Billing Factors:
        Defines the cost per unit for each resource type (e.g., GPU, CPU, memory).

Notes:

    This flowchart provides a general overview of the process. Specific details may vary depending on your system configuration and requirements.
    The flowchart uses simple shapes and clear labels for easy comprehension.
    The flow direction follows a top-down approach, starting from the cron job and ending with database closure.

<img width="831" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjQ3QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0ff176a6d62f46ea6be05f2169b2316100961015/mermaid-diagram-2023-12-06-141131.png" alt="mermaid-diagram-2023-12-06-141131.png" />
lity.

**Comment by trent-safe-ai** [comment]
We would need to do the following:

1) Create a database that we define for accounting and charge back.
2) Create/update the slurm.conf to incorporate billing factors- in the following example- a GPU hour = 10000 which would be translated in our accounting DB to whatever monetary value we assign- for simplicity- say $100/hr.
```
# Define TRES (Trackable RESources) for billing
AccountingStorageTRES=cpu,mem,gpu
PriorityType=priority/multifactor
PriorityUsageResetPeriod=NONE
PriorityWeightAge=0
PriorityWeightFairshare=0
PriorityWeightJobSize=0
PriorityWeightPartition=0
PriorityWeightQOS=0
PriorityWeightTRES=gres/gpu=10000
```

**Comment by trent-safe-ai** [comment]
We will need to add a couple things to the slurm,conf

```
AccountingStorageTRES=gres/gpu,gres/gpu:A100,cpu,mem
```
and
```
PriorityWeightTRES=gres/gpu:A100=100
PriorityWeightTRES=cpu=10
PriorityWeightTRES=mem=1

Then build tables in the mysql db on the bastion to reflect all the flags we would want from this command over the last day- (psuedo code)
```
sudo sacct -a --state=cd --format=JobID,User,Account,AllocTRES,AllocCPUS,MaxRSS,Elapsed --starttime="24 hours ago" --endtime=now
```

**Comment by trent-safe-ai** [comment]
Database psuedo code
```

**Comment by trent-safe-ai** [comment]
SQL

CREATE DATABASE slurm_billing;

USE slurm_billing;

CREATE TABLE user_resource_usage (
  user_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255) NOT NULL UNIQUE,
  date DATE NOT NULL,
  total_gpu_hours DECIMAL(10,2) NOT NULL,
  total_cpu_hours DECIMAL(10,2) NOT NULL,
  total_memory_gb_hours DECIMAL(10,2) NOT NULL
);

CREATE TABLE account_resource_usage (
  account_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  account_name VARCHAR(255) NOT NULL UNIQUE,
  date DATE NOT NULL,
  total_gpu_hours DECIMAL(10,2) NOT NULL,
  total_cpu_hours DECIMAL(10,2) NOT NULL,
  total_memory_gb_hours DECIMAL(10,2) NOT NULL
);

CREATE TABLE resource_billing_factors (
  resource_type VARCHAR(255) NOT NULL PRIMARY KEY,
  billing_factor DECIMAL(10,2) NOT NULL
);
```

**Comment by trent-safe-ai** [comment]
Psuedo code for the billing cron job:
```
import sacct
import datetime
import mysql.connector

# Define database connection information
db_host = "localhost"
db_user = "username"
db_password = "password"
db_name = "slurm_billing"

# Connect to database
db = mysql.connector.connect(host=db_host, user=db_user, password=db_password, database=db_name)
cursor = db.cursor()

# Define resource billing factors
resource_billing_factors = {
    "gres/gpu": 100.00,
    "cpu": 0.10,
    "mem": 0.001,
}

# Define the date range for collecting job data
today = datetime.date.today()
yesterday = today - datetime.timedelta(days=1)

# Collect job data for yesterday
jobs = sacct.jobs(start=yesterday, end=today, format="JobID,User,Account,AllocTRES,AllocCPUS,MaxRSS,State,Elapsed")

# Process and format the data
for job in jobs:
    job_id = job.JobID
    user = job.User
    account = job.Account
    tres = job.AllocTRES.split(",")
    allocated_cpus = int(job.AllocCPUS)
    max_rss = int(job.MaxRSS)
    state = job.State
    elapsed_time = job.Elapsed

    # Calculate resource usage
    resource_usage = {
        "total_gpu_hours": 0.0,
        "total_cpu_hours": 0.0,
        "total_memory_gb_hours": 0.0,
    }
    for resource in tres:
        resource_type, resource_value = resource.split("=")
        resource_value = float(resource_value)

        if resource_type == "gres/gpu":
            resource_usage["total_gpu_hours"] += resource_value
        elif resource_type == "cpu":
            resource_usage["total_cpu_hours"] += resource_value * allocated_cpus
        elif resource_type == "mem":
            resource_usage["total_memory_gb_hours"] += resource_value * max_rss / 1024**3

    # Calculate total cost
    total_cost = 0.0
    for resource_type, usage in resource_usage.items():
        billing_factor = resource_billing_factors.get(resource_type, 0.0)
        cost = usage * billing_factor
        total_cost += cost

    # Prepare data for insertion
    insert_data = {
        "user_id": user,
        "date": today,
        "total_gpu_hours": resource_usage["total_gpu_hours"],
        "total_cpu_hours": resource_usage["total_cpu_hours"],
        "total_memory_gb_hours": resource_usage["total_memory_gb_hours"],
    }

    # Insert data into user and account tables
    cursor.execute("INSERT INTO user_resource_usage (username, date, total_gpu_hours, total_cpu_hours, total_memory_gb_hours) VALUES (%s, %s, %s, %s, %s)",
        (insert_data["user_id"], insert_data["date"], insert_data["total_gpu_hours"], insert_data["total_cpu_hours"], insert_data["total_memory_gb_hours"]))
    cursor.execute("INSERT INTO account_resource_usage (account_name, date, total_gpu_hours, total_cpu_hours, total_memory_gb_hours) VALUES (%s, %s, %s, %s, %s)",
        (account, insert_data["date"], insert_data["total_gpu_hours"], insert_data["total_cpu_hours"], insert_data["total_memory_gb_hours"]))

# Commit changes to the database
db.commit()

# Close database connection
cursor.close()
db.close()
```

**Comment by trent-safe-ai** [comment]
@steven-basart @andriy-safe-ai  please take a look at this basic idea for creating a billing database for daily resource consumption by user and account- let me know if you have questions- Id like to test this in dev first.

**Comment by andriy-safe-ai** [comment]
@trent-safe-ai 

I like the idea of a billing database. If fact I'm working on converting my solution to track network egress per user to use a relational database. I currently have a solution which logs the data to files periodical with the help on a cron job which are then processed by a script when we need to calculate total usage. After reviewing with Steven, we've decided that using a database instead of log files and custom scripts would be a better direction to go to. I haven't looked into which specific databases we would use but for the kind of data that we would like to store I think relational database that's optimized for time series data would be the way to go. If you have suggestions for this let me know. 

I'd like to add another table for the network egress data:
```
CREATE TABLE network_egress_usage_hourly (
    user_id INT NOT NULL FOREIGN KEY,
    date DATE NOT NULL,
    bytes INT NOT NULL
);
```

To track network egress we are using `iptables` byte counters. They can accurately capture the quantity of network traffic but they reset if a node is rebooted so I would like to capture these counters more frequently than once a day so prevent data loss. When I capture the byte counters I also reset them. So each row would be how much data a user moved out of the cluster in an hour. We would have two cron jobs. One to capture GPU, CPU, Memory usage from slurm and another to capture network egress usage from `iptables`. Let me know what your thoughts are on this.

Other comments:
- What does "account" mean in this context? 
- Why do you have usage columns in the user and the account tables? Wouldn't we be able to calculate the usage of an account by totaling the usage of all the users in the account? I'm not sure what an account is in this context so please clarify.
- To add to the above comment, I think we're missing a FOREIGN KEY to the account table in the user table.
- **We need track what kinda of GPU or CPU is getting used**. An hour of A100 and H100 are not the same for example. 
- What do you think about creating a separate table for `user`, `gpu_usage`, `gpu_type`, `cpu_usage`, `cpu_type`, etc..?

I found this insightful: https://support.cs.toronto.edu/systems/slurmresource.html

**Comment by trent-safe-ai** [comment]
What does "account" mean in this context?
**'Account' is the lab, grouping of users from the sacct command and we want account usage and per user usage.**

    Why do you have usage columns in the user and the account tables? Wouldn't we be able to calculate the usage of an account by totaling the usage of all the users in the account? I'm not sure what an account is in this context so please clarify.
    **We need to know the total alloc resources per day per account/lab and per user.**

    To add to the above comment, I think we're missing a FOREIGN KEY to the account table in the user table.
   ** Yep will be added to final DB data structure**
    We need track what kinda of GPU or CPU is getting used. An hour of A100 and H100 are not the same for example.
    What do you think about creating a separate table for user, gpu_usage, gpu_type, cpu_usage, cpu_type, etc..?

   **Yes- we would need to add H100 to the AccountingStorageTRES line in slurm.conf- and yea we can design the DB a little better- i'll put together the requirements and add your recommendations to it and put the code for the DB creation in this issue.**

**Comment by andriy-safe-ai** [comment]
Billing system added in #250
