### ISSUE TITLE
Add Passwordless SSH for root user

### ISSUE THREAD

**Issue by andriy-safe-ai** [centerforaisafety/cerberus-cluster#278]
We need this to upgrade Weka.

**Comment by steven-basart** [comment]
Make sure you reverse this when you're done

**Comment by andriy-safe-ai** [comment]
I plan to add playbooks that we can run to enable/disable passwordless SSH for root. We will need this in the future when we have to upgrade again.

**Comment by steven-basart** [comment]
Can you add a thing where it leaves a note in the splash screen saying if we've left passwordless SHH on?  I just really really want to make sure it's off and we remember to turn it off. Open to other suggestions
