### ISSUE TITLE
Turn off swap on all machines

### ISSUE THREAD

**Issue by xksteven** [centerforaisafety/cerberus-cluster#38]
```sudo swapoff -a```

**Comment by AndriyNovykov** [comment]
Why would we want to turn off swap?

**Comment by xksteven** [comment]
## Story time

I hate swap. It's so old school. 

### When is it used?

Program is consuming too much RAM. okay so what should happen now? Let's use the 100x slower memory of flash or God forbid hard disk to temporarily store it and retrieve it later. 

That doesn't sound so bad right?

Okay now practically speaking when does it happen. 

We have a program that has an infinite loop and is consuming all of the RAM and resources. 

What happens next?

Well the operating system steps in to save this program by allocating even More memory to this program because if you add a tiny bit more it'll surely work right?

What happens next?

The entire node is sitting waiting on I/O because it just needs a little bit more memory to do the next step of execution for this program and now the entire node is essentially unresponsive because CPUs are basically only working to swap out RAM space for swap space and repeating this process for all eternity.

Meanwhile what am I trying to do?

I am just trying to either Ctrl+C to kill the program or typing `kill -9 pid` to kill it. The operating system won't even listen to me though because it's too busy trying to save this program. 

###  Alternate universe.

Here's the alternative universe where it's dead or non existent.

Program consumes all the memory and requests more. 

Operating system tells program that there is no more memory and proceed to just kill the program. This all happened within a few seconds tops and I'm literally none the wiser as an admin. 

### Conclusion 

Hope that helps explain why I want it dead.

**Comment by steven-basart** [comment]
Merged.  Closing Issue.
