### ISSUE TITLE
Add docker support

### ISSUE THREAD

**Issue by steven-basart** [centerforaisafety/cerberus-cluster#45]

**Comment by rumiahkessel** [comment]
Can you expand on what is needed for this to happen? All of the benchmarking tools I have found thus far rely on docker to make them portable and reviewable. If we want to use the industry standard metrics we will want to do it using docker. Happy to look into this

**Comment by steven-basart** [comment]
We already have both docker and pyxis installed on the cluster.
Remaining actions required:
Can we pull docker images?
Can we push to dockerhub?
Can we build a new image?
What are the steps to get slurm to run a docker container for a user?
We also need to write the documetation for it.
Slurm does integrate with docker nicely (and other cotainerization tools).  I'd prefer to have slurm do a docker deploy then having users sbatch or srun then manually launch docker.

I think there's a command like

```
srun --container blah
```

**Comment by steven-basart** [comment]
For some additional context. We have both docker and pyxis installed on the cluster already. 
Things that need to done for this ticket.
Can we pull docker images?
Can we push to docker hub?
Can users build a container locally?
What are the steps are required to run docker on the cluster?
Does the slurm docker integration work?
The documentation for the users also needs to be written.

**Comment by andriy-safe-ai** [comment]
@steven-basart 

#148 

Closing.
