### ISSUE TITLE
Add email notifications to Slurm

### ISSUE THREAD

**Issue by AndriyNovykov** [centerforaisafety/cerberus-cluster#47]
# Slurm Notifications

On our HPC cluster, we utilize the Slurm job scheduler to allocate compute time fairly among our users. Slurm is a widely-used job scheduler in the HPC domain. If you want to learn more about Slurm, you can refer to their documentation available at [Slurm Docs](https://slurm.schedmd.com/overview.html).

Currently, our users need to manually check the status of their jobs, which can be a cumbersome process. To streamline this, we aim to enable email notifications for our users. With this enhancement, users can optionally receive notifications via email when their Slurm jobs start, complete, fail, and so on. Although Slurm supports this feature, it requires some configuration.

To facilitate your work, we will provide you with a development cluster that is already configured with Slurm. However, please note that you will not have production access. You can utilize the development cluster to develop and test your solution. Once your solution is ready for production, we expect you to provide step-by-step instructions for setting up email notifications on the development environment. Furthermore, you should detail how this setup can be replicated in our production environment.

After you have tested your solution on the development cluster and it meets our requirements, we will proceed with deploying your solution in the production environment.

As an optional task, you can also explore the implementation of other forms of notifications, such as Slack notifications. However, it is important to prioritize and keep in mind that email notifications are the minimum viable product (MVP) for this project.

## Cluster Documentation Links:
https://cluster.safe.ai/#slurm-notes
https://docs.cais.tools/

**Comment by rumiahkessel** [comment]
Steps for setting up mail notifications:

1. First make a new safe.ai email account that will be the email sending job notifications.
2. Enable 2fa for the account [https://myaccount.google.com/security](https://myaccount.google.com/security). Make sure you select the new account on the login screen or change to it in the top right corner.
3. Now go to: [https://myaccount.google.com/apppasswords](https://myaccount.google.com/apppasswords). Again ensure you are on the new account.
4. Press the "select app" dropdown and select "other". Then enter any name you like such as "Slurm Job Notifications". This will only be used here but should be recognizable.
5. Press "Generate" in the bottom right and copy this password (it will be used in a few steps)
6. Now log in to the production server and become the root (needed only for the following command the rest can be done by any admin)
7. Run `sudo systemctl restart postfix` then `sudo systemctl enable postfix`. These commands restart the mail server then set it to enable on server startup. This should give crash resistance for this service, but should be checked (`sudo systemctl status postfix`) in the event of a bastion crash in the future.
8. This step is optional as the MailProg slurm variable default is correctly directed here, but to be clear I recommend doing this. navigate to `/bin` and check that "mail" (case matters) is there. If it isn't there then mailx needs to be installed on the server and this might mean a different setup than the development server. If it is there then we can edit `/etc/slurm/slurm.conf` and add the line: `MailProg=/bin/mail` to the config file to a relevant section (user preference).
9. Now edit '/etc/mail.rc' and add the following code after `set dot` where you replace $PASSWORD with the app password from before, $EMAIL with the email address made for this, and $NAME with a plaintext name for users ex "Slurm Job Notifications" :
```
# SMTP settings
set smtp-use-starttls
set ssl-verify=ignore
set smtp=smtp://smtp.gmail.com:587
set smtp-auth=login
set smtp-auth-user=$EMAIL
set smtp-auth-password=$PASSWORD
set from="$EMAIL ($NAME)"
set nss-config-dir=/etc/pki/nssdb
```

All of the configuration is now done and a user can setup notifications by adding the following lines to their sbatch (replacing $USER_EMAIL with their email
```
#SBATCH --mail-user=$USER_EMAIL
#SBATCH --mail-type=ALL
```

**Comment by rumiahkessel** [comment]
Steps to follow after the previous ones to setup verbose messaging:

1.  First go to [this link](https://github.com/neilmunday/slurm-mail/releases/download/v4.4/slurm-mail-4.4-1.el7.noarch.rpm) to download the slurm-mail program. If that doesn't work go to [the releases](https://github.com/neilmunday/slurm-mail/releases) page and download the rpm package containing el7 (slurm-mail-4.4-1.el7.noarch.rpm). 
2. SCP that over to the production server in a relevant location that the root can access and install from
3. Run: `yum install slurm-mail-4.4-1.el7.noarch.rpm` Check that the slurm-send-mail and slurm-spool-mail binaries were added to /bin. If the binaries are not there you may need to run the install as root.
4. Set the MailProg variable in the /etc/slurm/slurm.conf file to be `MailProg=/bin/slurm-spool-mail`
5. Run: `sudo systemctl restart slurmctld`
6. Now edit `/etc/slurm-mail/slurm-mail.conf` and replace the entire file with the codeblock below (can delete and remake or just edit). Make sure to replace $EMAIL, $PASSWORD, and $NAME as described in the earlier comment. Additionally $SIGNATURE should be changed to the name signed at the bottom of the email Ex: ("SLURM Admin", "CAIS Team", etc).
```
[common]
# settings common to both scripts
spoolDir = /var/spool/slurm-mail

[slurm-spool-mail]
# slurm-spool-mail.py settings
logFile = /var/log/slurm-mail/slurm-spool-mail.log
verbose = false

[slurm-send-mail]
# slurm-send-mail.py settings
logFile = /var/log/slurm-mail/slurm-send-mail.log
verbose = false
arrayMaxNotifications = 0
emailFromUserAddress = $NAME
emailFromName = $SIGNATURE
emailRegEx = \b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b
emailSubject = Job $JOB_NAME on $CLUSTER.$JOB_ID: $STATE
validateEmail = false
datetimeFormat = %d/%m/%Y %H:%M:%S
sacctExe = /usr/bin/sacct
scontrolExe = /usr/bin/scontrol
smtpServer = smtp.gmail.com
smtpPort = 587
smtpUseTls = yes
smtpUseSsl = no
smtpUserName = $EMAIL
smtpPassword = $PASSWORD
tailExe = /usr/bin/tail
includeOutputLines = 5
```
7. Now be sure to change the permissions like we did in the earlier comment as this file contains a password.
```
sudo chown root:root /etc/slurm-mail/slurm-mail.conf
sudo chmod 600 /etc/slurm-mail/slurm-mail.conf
```

All the config should be complete and now verbose messaging is setup. Templates and more information can be adjusted as described in: [https://github.com/neilmunday/slurm-mail](https://github.com/neilmunday/slurm-mail)
