### ISSUE TITLE
Create new partition with only 1 node usable

### ISSUE THREAD

**Issue by steven-basart** [centerforaisafety/cerberus-cluster#53]
Add one of the compute nodes to that partition.
Add some new who users who only have access to that partition.
Test they don't have access to regular compute nodes.

**Comment by steven-basart** [comment]
We can add the Deny groups flag to the other partitions:
https://slurm.schedmd.com/slurm.conf.html#OPT_DenyGroups

Then create a new partition with the AllowGroups flag that overlaps with one of the interactive nodes.

**Comment by steven-basart** [comment]
Steps taken and final slurm.conf looks like the following:

```
PartitionName=compute Nodes=compute-hpc-node-[1-910],compute-permanent-node-[1-910] Default=YES DefaultTime=02:00:00 MaxTime=2-0 State=UP DenyAccounts=grads

PartitionName=interactive Nodes=compute-hpc-node-[911-1024],compute-permanent-node-[911-1024] Default=NO DefaultTime=00:30:00 MaxTime=00:30:00 State=UP
PartitionName=single Nodes=compute-hpc-node-[915-1024],compute-permanent-node-[915-1024] Default=NO DefaultTime=02:00:00 MaxTime=2-0 State=UP AllowGroups=grads
```
Which makes 1 node of the interactive partition available to "grads" group.

**Comment by andriy-safe-ai** [comment]
We need a PR for the `slurm.conf` changes.

**Comment by andriy-safe-ai** [comment]
@steven-basart 

I see have have documentation for this. Closing.
