### ISSUE TITLE
A few users seem to be misconfigured?

### ISSUE THREAD

**Issue by steven-basart** [centerforaisafety/cerberus-cluster#63]
Such as long_phan and possibly asa_cooper

**Comment by steven-basart** [comment]
To add the relevant details here. Long Phan wasn't showing up correctly under the `sacctmgr associations` I might've misconfigured him. I think his parent was root?

ASA cooper doesn't show up with PID search unlike other users. Check the GPU stats page while he's running something to see an example.

**Comment by andriy-safe-ai** [comment]
@steven-basart 

Long Phan seems to be configured correctly. When running `sudo sacctmgr show assoc`, Long Phan appears under the `cais` account. 

I've yet to see Asa Cooper run a job. I'm not sure whether he is still misconfigured.

**Comment by andriy-safe-ai** [comment]
Closing. Long isn't misconfigured and Asa was off boarded from the cluster.
