### ISSUE TITLE
Slurm backups

### ISSUE THREAD

**Issue by andriy-safe-ai** [centerforaisafety/cerberus-cluster#64]
We need backups for Slurm and PAM. Groups, Users, Slurm accounts, Slurm users we need backups for these. The restoration process needs to be simple, easy, and quick. These backups will be used for cluster restorations in emergencies. We don't want something that someone can mess-up in a stressful situation. We also want to use these backups to setup dev clusters with prod settings. We want these backups in two locations. One for use only in emergencies and another for development, etc.. Crazy things happen in development. We don't want to lose a backup while doing something in development and not have a backup available for prod. We don't expect these backups to be large (<1GB) so storage costs are not a concern.

**Comment by steven-basart** [comment]
Consult with Trent to avoid duplicate backups of slurm and other data.

**Comment by andriy-safe-ai** [comment]
#135
