### ISSUE TITLE
Get centralized location for our documentation

### ISSUE THREAD

**Issue by steven-basart** [centerforaisafety/cerberus-cluster#78]

**Comment by trent-safe-ai** [comment]
@steven-basart can we look at one these- integrating with github
[sphinx](https://github.com/sphinx-doc/sphinx)
[Jekyll](https://jekyllrb.com/docs/)
[mkdocs](https://www.mkdocs.org/)
Github Pages?

**Comment by steven-basart** [comment]
I've been formating our current documentation to be compatible with Jekyll by writing it in markdown. 

I think most of our docs can probably be public and the only things not public would be the user data. Which would keep on living in oke K8s walled garden. 

I'm pretty open to most solutions tbh. I just kind of want all of to take useful debugging notes for the rest of us in one location. Currently mine are in the info.cais.tools under admin docs but I'm happy to move them wherever. 

We'll probably just have a joint meeting. Pick our favorites then let ChatGPT decide which one will be best. 

Only other criterion I do care about is that docs be web accessible other than that just mostly want them to exist for all of us.

**Comment by trent-safe-ai** [comment]
@steven-basart makes sense I love the style of mkDocs and it matches the same model we have for the existing slurmd3 container- can have a static page build with every push to the documentation repo into a public documentation site that we can control with any type of auth we see fit. I'll do a test of that and see how easy it is. And this is indeed what GPT said-
`GitHub provides a variety of tools and features for creating and managing documentation. Here are some steps you can follow to create and manage documentation using GitHub:

    Create a new repository: To start, create a new repository on GitHub. You can name it something like "docs" or "documentation."

    Choose a documentation generator: There are many documentation generators available for GitHub, such as Sphinx, Jekyll, and MkDocs. Choose one that best suits your needs.

    Add documentation files: Once you've chosen a documentation generator, you can start adding documentation files to your repository. You can create separate folders for different types of documentation or organize them by topics.

    Use markdown: GitHub uses markdown to format and style documentation files. You can use markdown to create headings, links, lists, and more. GitHub also provides a markdown editor that allows you to preview your documentation as you write.

    Use GitHub Pages: GitHub Pages is a built-in feature that allows you to publish your documentation as a website. You can use a custom domain or a subdomain of github.io. You can also choose from a variety of themes to customize the look and feel of your documentation website.

    Use pull requests: If you're working with a team, you can use pull requests to review and collaborate on documentation changes. This allows you to ensure that your documentation is accurate, up-to-date, and consistent.

    Use GitHub Actions: GitHub Actions allows you to automate tasks, such as building and deploying your documentation website. You can create workflows that run automatically whenever you push changes to your repository.

By following these steps, you can create and manage high-quality documentation using GitHub.`

**Comment by steven-basart** [comment]
Closing this issue in favor of using:
https://github.com/centerforaisafety/eng-docs
