### ISSUE TITLE
Update git package

### ISSUE THREAD

**Issue by xksteven** [centerforaisafety/cerberus-cluster#8]
On all nodes

**Comment by xksteven** [comment]
Might have to follow this approach: https://stackoverflow.com/a/74028195/6416660
As default package is too old or check if a newer version exists on snap then add there.

**Comment by steven-basart** [comment]
This was completed in prod.  Double check the code base to see if prod and code differ.

**Comment by andriy-safe-ai** [comment]
Is there a PR for this?

**Comment by andriy-safe-ai** [comment]
@steven-basart 
Bump.

**Comment by steven-basart** [comment]
Yeah should close:
https://github.com/centerforaisafety/cerberus-cluster/blob/74f3c857a3844dfd8d42844a9333e317b03b189a/playbooks/roles/cais-all/tasks/ol-7.yml#L55

It's already been added to main a while ago and is in sync with prod.
