### ISSUE TITLE
Add --cpus-per-gpu=2 as a slurm default

### ISSUE THREAD

**Issue by steven-basart** [centerforaisafety/cerberus-cluster#86]
Add --cpus-per-gpu=2 or 4 as a default otherwise it defaults to 1 per whole task which is very tiny amount.

**Comment by steven-basart** [comment]
In slurm.conf add the following:

```
DefCpuPerGPU=2
```

**Comment by andriy-safe-ai** [comment]
@steven-basart 
Added in #130
