### ISSUE TITLE
Rebase code to latest OCI

### ISSUE THREAD

**Issue by steven-basart** [centerforaisafety/cerberus-cluster#96]

**Comment by andriy-safe-ai** [comment]
@steven-basart Has this been done? Is this a repeating task?

**Comment by steven-basart** [comment]
No this is rather time consuming task (imo). 
Last time I did this I squished all of our coffee to one commit and manually rebased then looked through all the files that have been changed to see what the changes are and how it affects us. 

Which changes should we port over to prod and potentially re-run.

**Comment by steven-basart** [comment]
Yes this was done.
